---
- name: Deploy update-cloudflare-ips script
  ansible.builtin.template:
    src: update-cloudflare-ips.sh.j2
    dest: /usr/local/bin/update-cloudflare-ips.sh
    mode: "0755"
    owner: root
    group: root

- name: Deploy Cloudflare IP update systemd service
  ansible.builtin.copy:
    src: cloudflare-ips-update.service
    dest: /etc/systemd/system/cloudflare-ips-update.service
    owner: root
    group: root
    mode: "0644"

- name: Deploy Cloudflare IP update systemd timer
  ansible.builtin.copy:
    src: cloudflare-ips-update.timer
    dest: /etc/systemd/system/cloudflare-ips-update.timer
    owner: root
    group: root
    mode: "0644"

- name: Enable and start Cloudflare IP update timer
  ansible.builtin.systemd:
    name: cloudflare-ips-update.timer
    state: started
    enabled: true
    daemon_reload: true
