- name: Install common software properties
  ansible.builtin.apt:
    name: software-properties-common
    state: present
    update_cache: true
    cache_valid_time: "{{ haproxy_cache_valid_time }}"
- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "ppa:vbernat/haproxy-{{ haproxy_version }}"
    state: present
- name: Install haproxy {{ haproxy_version }}
  ansible.builtin.apt:
    name: haproxy={{ haproxy_version }}.*
    state: present
    update_cache: true
    cache_valid_time: "{{ haproxy_cache_valid_time }}"
- name: Start the systemd service
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
    daemon_reload: true
