---
haproxy_tls_certificate_email: ""
haproxy_tls_certificate_haproxy_certs_dir: /etc/haproxy/certs
haproxy_tls_certificate_lego_cert_dir: "/etc/lego/certificates"
haproxy_tls_certificate_served_domains: []
# haproxy_tls_certificate_cloudflare_dns_api_token must be provided at runtime (no_log protected)
