galaxy_info:
  author: Meysam Azad
  description: Install HAProxy with apt
  company: Self employed

  license: Apache-2.0

  min_ansible_version: "2.17"

  platforms:
    - name: Debian
      versions:
        - all
        - bookworm
        - bullseye
        - buster
    - name: Ubuntu
      versions:
        - all
        - bionic
        - focal
        - jammy

  galaxy_tags:
    - haproxy
    - loadbalancer
    - proxy
    - reverseproxy
    - webserver
    - web

dependencies: []
