namespace: meysam81
name: general
version: 1.4.10
readme: README.md
authors:
  - Meysam Azad <meysam@developer-friendly.blog>
description: A collection of personal & opinionated Ansible roles
license:
  - Apache-2.0
tags:
  - application
  - cloud
  - database
  - infrastructure
  - linux
  - monitoring
  - networking
  - security
  - storage
  - tools
dependencies: {}
repository: https://github.com/meysam81/ansible-collections
documentation: https://meysam81.github.io/ansible-collections
homepage: https://meysam81.github.io/ansible-collections
issues: https://github.com/meysam81/ansible-collections/issues
build_ignore: []
