- name: Demo
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Ping
      ansible.builtin.ping:
  roles:
    - role: haproxy
      tags: haproxy
    - role: node_exporter
      tags: node_exporter
    - role: vmagent
      tags: vmagent
      vars:
        vmagent_remote_write_url: "{{ lookup('env', 'VMAGENT_REMOTE_WRITE_URL') | default('http://localhost:8428/api/v1/write', true) }}"
    - role: promtail
      tags: promtail
      vars:
        promtail_remote_write_url: "{{ lookup('env', 'PROMTAIL_REMOTE_WRITE_URL') | default('http://localhost:3100/loki/api/v1/push', true) }}"
    - role: pushgateway
      tags: pushgateway
