- name: Test roles
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Ping
      ansible.builtin.ping:
  roles:
    - role: haproxy
      tags: haproxy
    - role: node_exporter
      tags: node_exporter
    - role: vmagent
      tags: vmagent
      vars:
        vmagent_remote_write_url: "{{ lookup('env', 'VMAGENT_REMOTE_WRITE_URL') | default('http://localhost:8428/api/v1/write', true) }}"
    - role: promtail
      tags: promtail
      vars:
        promtail_remote_write_url: "{{ lookup('env', 'PROMTAIL_REMOTE_WRITE_URL') | default('http://localhost:3100/loki/api/v1/push', true) }}"
    - role: pushgateway
      tags: pushgateway
    - role: k8s_oidc_github_pages
      tags: k8s_oidc_github_pages
    - role: kratos
      tags: kratos
    - role: oathkeeper
      tags: oathkeeper
    - role: k8s_oidc_github_pages
      tags: k8s_oidc_github_pages
    - role: vm_identity_gcp
      tags: vm_identity_gcp
