---
- name: Download and read sha256sum file
  ansible.builtin.set_fact:
    sha256sum_file_content: "{{ lookup('ansible.builtin.url', promtail_sha256sum_url, wantlist=True) }}"
  when: promtail_version and promtail_sha256sum_url
- name: Extract SHA256 checksums for {{ promtail_url | basename }}
  ansible.builtin.set_fact:
    sha256sum: "{{ sha256sum_file_content | select('search', promtail_url | basename) | map('split', ' ') | map('first') | list | first }}"
  when: promtail_version and promtail_sha256sum_url
- name: Download promtail
  ansible.builtin.get_url:
    url: "{{ promtail_url }}"
    dest: "/tmp/{{ promtail_url | basename }}"
    mode: "0444"
    owner: "{{ promtail_user }}"
    group: "{{ promtail_group }}"
    checksum: "{{ 'sha256:' + sha256sum if sha256sum else None }}"
  register: promtail_download
- name: Extract promtail
  ansible.builtin.unarchive:
    src: "/tmp/{{ promtail_url | basename }}"
    dest: /tmp/
    owner: root
    group: root
    remote_src: true
  register: promtail_extract
  when: promtail_download.changed
- name: Install promtail binary
  ansible.builtin.copy:
    src: "{{ promtail_extract.files | first }}"
    dest: /usr/local/bin/promtail
    owner: root
    group: root
    mode: "0555"
  notify: Restart promtail
- name: Create promtail relevant dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: promtail
    group: promtail
    mode: "0755"
  loop:
    - /etc/promtail
    - /var/lib/promtail
- name: Fetch promtail remote write password file
  ansible.builtin.copy:
    content: "{{ promtail_remote_write_password }}"
    dest: /var/lib/promtail/remote-password-file
    owner: promtail
    group: promtail
    mode: "0400"
  no_log: true
  notify: Restart promtail
  when: promtail_remote_write_password is defined
- name: Copy promtail config file
  ansible.builtin.template:
    src: promtail.yml.j2
    dest: /etc/promtail/promtail.yml
    owner: promtail
    group: promtail
    mode: "0440"
  notify: Restart promtail
- name: Create promtail service
  ansible.builtin.template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart promtail
- name: Start promtail service
  ansible.builtin.systemd:
    name: promtail
    state: started
    enabled: true
    daemon_reload: true
