- name: Create group {{ promtail_group }}
  ansible.builtin.group:
    name: "{{ promtail_group }}"
    state: present
    system: true
  register: created_group
- name: Create user {{ promtail_user }}
  ansible.builtin.user:
    name: "{{ promtail_user }}"
    state: present
    system: true
    shell: /bin/false
    create_home: true
    group: "{{ created_group.name }}"
    groups:
      - adm
