---
- name: Disable conflicting DNS resolvers
  ansible.builtin.include_tasks: disable-resolvers.yml
  when: dnsproxy_disable_resolvers

- name: Setup dnsproxy on Debian/Ubuntu
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
