---
node_exporter_arch: "{{ (ansible_architecture | default('amd64')) | replace('x86_64', 'amd64') }}"
node_exporter_create_user: true
node_exporter_download_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version | regex_replace('^v', '') }}/node_exporter-{{ node_exporter_version | regex_replace('^v', '') }}.{{ node_exporter_os }}-{{ node_exporter_arch }}.tar.gz # yamllint disable-line rule:line-length
node_exporter_group: node-exporter
node_exporter_healthcheck_enabled: true
node_exporter_os: linux
node_exporter_owner: node-exporter
node_exporter_sha256sum_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version | regex_replace('^v', '') }}/sha256sums.txt
node_exporter_version: 1.8.2
