---
kratos_arch: "{{ (ansible_architecture | default('amd64')) | replace('x86_64', '64bit') | replace('aarch64', 'arm64') }}"
kratos_checksum_url: https://github.com/ory/kratos/releases/download/v{{ kratos_version | regex_replace('^v', '') }}/checksums.txt
kratos_configuration: |
  dsn: memory

  courier:
    smtp:
      # checkov:skip=CKV_SECRET_4:Basic Auth Credentials
      connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

  selfservice:
    default_browser_return_url: http://example.com

  identity:
    schemas:
      - id: default
        url: https://github.com/ory/kratos/raw/refs/tags/v{{ kratos_version | regex_replace('^v', '') }}/contrib/quickstart/kratos/email-password/identity.schema.json
kratos_download_url: >-
  https://github.com/ory/kratos/releases/download/v{{ kratos_version | regex_replace('^v', '') }}/kratos_{{ kratos_version | regex_replace('^v', '') }}-{{ kratos_os }}{{ kratos_sqlite | ternary('_sqlite', '') }}{{ kratos_libmusl | ternary('_libmusl', '') }}_{{ kratos_arch }}.tar.gz
kratos_envs: {}
kratos_exec_cmd: /usr/local/bin/kratos serve
kratos_group: kratos
kratos_libmusl: false
kratos_os: linux
kratos_sqlite: true
kratos_user: kratos
kratos_version: 1.3.1
