---
galaxy_info:
  author: Meysam Azad
  role_name: sysctl
  description: Manage sysctl kernel parameters via drop-in configuration files
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble
  license: Apache-2.0
allow_duplicates: false

dependencies: []
