---
- name: Start haproxy service
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
    daemon_reload: true

- name: Reload haproxy service
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
    enabled: true
    daemon_reload: true
  register: _haproxy_reload
  failed_when:
    - _haproxy_reload.failed
    - not (lookup('env', 'CI') | default('false') | bool)
