---
galaxy_info:
  author: Meysam Azad
  role_name: crowdsec_haproxy_bouncer
  description: CrowdSec HAProxy bouncer (Lua-based SPOE)
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble
  license: Apache-2.0
allow_duplicates: false

dependencies:
  - role: haproxy_base
