---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  vars:
    haproxy_backends:
      - name: app
        servers:
          - { name: sv0, address: "127.0.0.1", port: 80 }
        health_check: "GET /healthz"
    haproxy_routes:
      - match: { host_suffix: "example.com" }
        backend: app
  pre_tasks:
    - name: Ping
      ansible.builtin.ping:
    - name: Generate test TLS certificate for HAProxy
      ansible.builtin.include_tasks: ../../tests/generate-test-cert.yml
      tags: haproxy
  tasks:
    - name: Copy relabling config
      ansible.builtin.copy:
        content: |
          - source_labels:
              - exported_job
            action: replace
            target_label: job
            regex: (.+)
          - source_labels:
              - exported_instance
            action: replace
            target_label: instance
            regex: (.+)
        dest: /etc/vmagent/relablings.yml
        owner: vmagent
        group: vmagent
        mode: "0644"
      notify: Restart vmagent service
      tags: vmagent
    - name: Ensure vmagent.service is running
      ansible.builtin.command: systemctl status vmagent
      register: vmagent_service_status
      changed_when: false
      tags: vmagent
  roles:
    - role: golang
      tags: golang
    - role: haproxy
      tags: haproxy
    - role: tls_certificate
      tags: tls_certificate
      vars:
        tls_certificate_email: "{{ lookup('env', 'TLS_CERT_EMAIL') | default('admin@example.com', true) }}"
        tls_certificate_cloudflare_dns_api_token: "{{ lookup('env', 'CLOUDFLARE_DNS_API_TOKEN') | default('dummy', true) }}"
    - role: cloudflare_ips
      tags: cloudflare_ips
    - role: coraza
      tags: coraza
    - role: crowdsec
      tags: crowdsec
    - role: node_exporter
      tags: node_exporter
    - role: vmagent
      tags: vmagent
      vars:
        vmagent_remote_write_url: "{{ lookup('env', 'VMAGENT_REMOTE_WRITE_URL') | default('http://localhost:8428/api/v1/write', true) }}"
        vmagent_allow_insecure_url: true
        vmagent_extra_cli_flags:
          - -remoteWrite.urlRelabelConfig=/etc/vmagent/relablings.yml
    - role: promtail
      tags: promtail
      vars:
        promtail_remote_write_url: "{{ lookup('env', 'PROMTAIL_REMOTE_WRITE_URL') | default('http://localhost:3100/loki/api/v1/push', true) }}"
        promtail_allow_insecure_url: true
    - role: pushgateway
      tags: pushgateway
