---
role_name_check: 1

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  options:
    vv: true
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: .molecule/.facts
      fact_caching_timeout: 7200
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible

lint: |
  yamllint .
  ansible-lint
