---
- name: Reload vmagent service
  ansible.builtin.systemd:
    name: vmagent
    state: reloaded
    daemon_reload: true
- name: Restart vmagent service
  ansible.builtin.systemd:
    name: vmagent
    state: restarted
    daemon_reload: true
