---
- name: Check installed lego version
  ansible.builtin.command:
    cmd: "{{ lego_bin_dir }}/lego --version"
  register: lego_installed_version
  changed_when: false
  failed_when: false

- name: Set lego install needed flag
  ansible.builtin.set_fact:
    lego_needs_install: "{{ lego_installed_version.rc != 0 or lego_version not in (lego_installed_version.stdout | default('')) }}"

- name: Install Lego
  ansible.builtin.include_tasks: install-lego.yml
  when: lego_needs_install or ( lego_force_download | bool )
