---
- name: Start coraza-spoa service
  ansible.builtin.systemd:
    name: coraza-spoa.service
    state: started
    enabled: true
    daemon_reload: true

- name: Restart coraza-spoa service
  ansible.builtin.systemd:
    name: coraza-spoa.service
    state: restarted
    enabled: true
    daemon_reload: true
