---
golang_version: "1.26.0"
golang_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
golang_os: "linux"
golang_install_dir: "/usr/local"
golang_download_url: "https://go.dev/dl/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"
golang_checksum_url: "{{ golang_download_url }}.sha256"
