---
vmagent_arch: "{{ (ansible_architecture | default('amd64')) | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}"
vmagent_bin: /usr/local/bin/vmagent-prod
vmagent_docker_enabled: false
vmagent_extra_labels: {}
vmagent_fail2ban_enabled: false
vmagent_group: vmagent
vmagent_haproxy_exporter_enabled: false
vmagent_http_listen_addr: 127.0.0.1:8429
vmagent_instance_label: ""
vmagent_mongo_exporter_enabled: false
vmagent_node_exporter_enabled: false
vmagent_os: linux
vmagent_pushgateway_enabled: false
vmagent_redis_exporter_enabled: false
vmagent_remote_write_force_vm_proto: false
vmagent_remote_write_password: ""
vmagent_remote_write_token_file: ""
vmagent_remote_write_username: ""
vmagent_scrape_interval: 30s
vmagent_user: vmagent
vmagent_version: 1.104.0
vmagent_vmutils_url: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ vmagent_version | regex_replace('^v', '') }}/vmutils-{{ vmagent_os }}-{{ vmagent_arch }}-v{{ vmagent_version | regex_replace('^v', '') }}.tar.gz
